### ISSUE TITLE
Record WebHook responses

### ISSUE THREAD

**Issue by paulbjensen** [webcast-io/jobukyu#17]
If you have a WebHook, and you get back a non-200 response (404, 403, 422, 500), then it might be valuable to record that somewhere, so that the user can see that their web hooks have an error, or didn't go through for some reason.

**Comment by bencevans** [comment]
Should add logging even for the successful request/responses and possibly add
an easy method to replay the hook too

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
